// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBXeny09PvkNlHriLBEfUbkla_sqCkvcnQ",
    authDomain: "mywallet-becce.firebaseapp.com",
    projectId: "mywallet-becce",
    storageBucket: "mywallet-becce.firebasestorage.app",
    messagingSenderId: "1042834635095",
    appId: "1:1042834635095:web:3e2c56fe3a1ac63295a612",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT5q-JsTeZqVgwLDTc5CbiatQjndDkwkU',
    appId: '1:1042834635095:android:26664acbc8c7444795a612',
    messagingSenderId: '1042834635095',
    projectId: 'mywallet-becce',
    storageBucket: 'mywallet-becce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR4396fIqZP9xGJlEsQpjJrPmh8KZX3AM',
    appId: '1:1042834635095:ios:88d89617630b21db95a612',
    messagingSenderId: '1042834635095',
    projectId: 'mywallet-becce',
    storageBucket: 'mywallet-becce.firebasestorage.app',
    iosClientId:
        '1042834635095-mmqj80hq5i6kvvilnkd91b3eshd442mo.apps.googleusercontent.com',
    iosBundleId: 'com.example.mywallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR4396fIqZP9xGJlEsQpjJrPmh8KZX3AM',
    appId: '1:1042834635095:ios:88d89617630b21db95a612',
    messagingSenderId: '1042834635095',
    projectId: 'mywallet-becce',
    storageBucket: 'mywallet-becce.firebasestorage.app',
    iosClientId:
        '1042834635095-mmqj80hq5i6kvvilnkd91b3eshd442mo.apps.googleusercontent.com',
    iosBundleId: 'com.example.mywallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXeny09PvkNlHriLBEfUbkla_sqCkvcnQ',
    appId: '1:1042834635095:web:529200eab819bed095a612',
    messagingSenderId: '1042834635095',
    projectId: 'mywallet-becce',
    authDomain: 'mywallet-becce.firebaseapp.com',
    storageBucket: 'mywallet-becce.firebasestorage.app',
    measurementId: 'G-CZB7C36GPM',
  );
}
